language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
services:
- redis-server
env:
  global:
  - secure: LD0/aeZ4yCodxjrOQgYJYZzuoHw0MqoRAq5V6mkmcFbq9D2E1a9nE8dGv4IxFoAyY4Zg5r6uTAtTd5d4L09vT3H0KHnO59NEktUjRMFu24yal83g8Y4U+aaj4NAWebaioq9VVMVlmBrnJKtV972ApzgeslazqEW3u+z0HOBS8ik=
  - secure: XUGLTP7rqOxYXZMob6Uqc4uoUpIypP3DO+U6JUChZHLsCqM3SROnGDiaUOqusWoR4a8XxE6S2GCzXYa80hfCof1vtWfcEdPZSwMF4Ue/xR1LR4JTBTayOmJTTSnR6e29MhSPK/nIVXbDTeJsY8ctCSvZFOyrOTp6k1xyBcbKEDI=
  - secure: acqb/Dua5RNOUEOqU4fVIg2gd93OJW9j26gT5QhFFHFSXSdTDQoP++O7yc3tPyzvopG96BnNSRJNfolskiDXy8/z9+IJpBhGEpYMmSceHBOSOCYCvsdpYBCRjgWya8Di1THCNQV0B4hBKilR0rnlww58zx65TYY2Y2c0eB5ToV4=
  - secure: Mcv5fU7hpiQBZ2KHr0gevHpvTiqIGNIfKa4vyUawlbiL5vnByWudlJLSd2e+Vz9JwP3K0k+4p/PeIUn6W52Nisn6KEvTJfGKxnL4IT4ea86xnSeKQWScQW6QrKWI9+gPmrIT5bMM82mzEt+fvA6aAjRl/diq7iJw5xKjclntQAw=
  - secure: WG9Kp4V3DfSqvmOV+FlwQtYlCOWUDKaC9XMpTZUd1rxLNSlVpHbXSLwJXhDcY4HHdD4A9eHDhckIdc+IpQwygwI6cBscfZNBVdq/w3Yjhujh8qLDR1dX4fCrCL3jMOMyrkZ2g8i/dBNtLvIwYA+sRikVqNztovbWFQh6oAYqVgA=
